senate_district = {
    'san juan': 'San Juan',
    'aguas buenas': 'San Juan',
    'guaynabo': 'San Juan',
    'bayamon': 'Bayamón',
    'bayamón': 'Bayamón',
    'catano': 'Bayamón',
    'cataño': 'Bayamón',
    'toa alta': 'Bayamón',
    'toa baja': 'Bayamón',
    'arecibo': 'Arecibo',
    'barceloneta': 'Arecibo',
    'camuy': 'Arecibo',
    'ciales': 'Arecibo',
    'dorado': 'Arecibo',
    'florida': 'Arecibo',
    'hatillo': 'Arecibo',
    'manati': 'Arecibo',
    'manatí': 'Arecibo',
    'morovis': 'Arecibo',
    'quebradillas': 'Arecibo',
    'vega alta': 'Arecibo',
    'vega baja': 'Arecibo',
    'aguada': 'Mayagüez',
    'aguadilla': 'Mayagüez',
    'anasco': 'Mayagüez',
    'añasco': 'Mayagüez',
    'cabo rojo': 'Mayagüez',
    'hormigueros': 'Mayagüez',
    'isabela': 'Mayagüez',
    'las marias': 'Mayagüez',
    'las marías': 'Mayagüez',
    'mayaguez': 'Mayagüez',
    'mayagüez': 'Mayagüez',
    'moca': 'Mayagüez',
    'rincon': 'Mayagüez',
    'rincón': 'Mayagüez',
    'san german': 'Mayagüez',
    'san germán': 'Mayagüez',
    'san sebastian': 'Mayagüez',
    'san sebastián': 'Mayagüez',
    'adjuntas': 'Ponce',
    'guanica': 'Ponce',
    'guánica': 'Ponce',
    'jayuya': 'Ponce',
    'juana diaz': 'Ponce',
    'juana díaz': 'Ponce',
    'lajas': 'Ponce',
    'lares': 'Ponce',
    'maricao': 'Ponce',
    'penuelas': 'Ponce',
    'peñuelas': 'Ponce',
    'ponce': 'Ponce',
    'sabana grande': 'Ponce',
    'utuado': 'Ponce',
    'yauco': 'Ponce',
    'aibonito': 'Guayama',
    'arroyo': 'Guayama',
    'barranquitas': 'Guayama',
    'cayey': 'Guayama',
    'cidra': 'Guayama',
    'coamo': 'Guayama',
    'comerio': 'Guayama',
    'comerío': 'Guayama',
    'corozal': 'Guayama',
    'naranjito': 'Guayama',
    'orocovis': 'Guayama',
    'salinas': 'Guayama',
    'santa isabel': 'Guayama',
    'villalba': 'Guayama',
    'caguas': 'Humacao',
    'gurabo': 'Humacao',
    'humacao': 'Humacao',
    'juncos': 'Humacao',
    'las piedras': 'Humacao',
    'maunabo': 'Humacao',
    'naguabo': 'Humacao',
    'patillas': 'Humacao',
    'san lorenzo': 'Humacao',
    'yabucoa': 'Humacao',
    'canovanas': 'Carolina',
    'canóvanas': 'Carolina',
    'ceiba': 'Carolina',
    'culebra': 'Carolina',
    'fajardo': 'Carolina',
    'loiza': 'Carolina',
    'loíza': 'Carolina',
    'luquillo': 'Carolina',
    'rio grande': 'Carolina',
    'río grande': 'Carolina',
    'trujillo alto': 'Carolina',
    'vieques': 'Carolina'
}